name: CI

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - "**/*.log"
      - "**/*.json"
      - "**/*.xml"
      - "**/*.png"
      - "**/*.svg"
      - "**/*.pptx"
      - "**/*.ppt"
      - "**/*.pdf"
      - "**/*.docx"
      - "**/*.doc"
      - "**/*.xls"
      - "**/*.xlsx"
      - ".ai/**"
      - "docs/**"
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - "**/*.log"
      - "**/*.json"
      - "**/*.xml"
      - "**/*.png"
      - "**/*.svg"
      - "**/*.pptx"
      - "**/*.ppt"
      - "**/*.pdf"
      - "**/*.docx"
      - "**/*.doc"
      - "**/*.xls"
      - "**/*.xlsx"
      - ".ai/**"
      - "docs/**"

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository (no submodules in single step)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: 0
          submodules: 'false'

      - name: Checkout WelsonJS (submodules)
        uses: actions/checkout@v5
        with:
          repository: gnh1201/welsonjs
          path: WelsonJS
          fetch-depth: 0
          fetch-tags: 0
          

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Get USERPROFILE and set CACHE_PATH
        id: set_cache_path
        shell: pwsh
        run: |
            $userProfile = [System.Environment]::GetEnvironmentVariable("USERPROFILE")
            $cachePath = Join-Path $userProfile ".nuget\packages"
            echo "CACHE_PATH=$cachePath" >> $env:GITHUB_ENV
    
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ${{ env.CACHE_PATH }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: |
          dotnet restore src/Core/Core.csproj
          dotnet restore src/ManagementWeb/ManagementWeb.csproj
          dotnet restore src/ManagementCli/ManagementCli.csproj
          dotnet restore tests/Core.Tests/Core.Tests.csproj
          dotnet restore tests/ManagementWeb.Tests/ManagementWeb.Tests.csproj

      - name: Build (excluding AuthProvider)
        run: |
          dotnet build src/Core/Core.csproj --configuration Release --no-restore
          dotnet build src/ManagementWeb/ManagementWeb.csproj --configuration Release --no-restore
          dotnet build src/ManagementCli/ManagementCli.csproj --configuration Release --no-restore

      - name: Test (exclude AuthProvider tests)
        run: |
          dotnet test tests/Core.Tests/Core.Tests.csproj --configuration Release --logger trx
          dotnet test tests/ManagementWeb.Tests/ManagementWeb.Tests.csproj --configuration Release --logger trx

    
    