name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build (excluding AuthProvider)
        run: |
          dotnet build src/Core/Core.csproj --configuration Release --no-restore
          dotnet build src/ManagementWeb/ManagementWeb.csproj --configuration Release --no-restore
          dotnet build src/ManagementCli/ManagementCli.csproj --configuration Release --no-restore

      - name: Test (exclude AuthProvider tests)
        run: |
          dotnet test tests/Core.Tests/Core.Tests.csproj --configuration Release --no-build --logger trx
          dotnet test tests/ManagementWeb.Tests/ManagementWeb.Tests.csproj --configuration Release --no-build --logger trx

    